rootProject.name = "ATSY Cast"
include(":gs-mm")
include(":tiktok")
include(":gsmovies")
include(":eporner")
include(":2d")
include(":ets2mm")
include(":doujin")
include(":zcm")
include(":msys")
include(":msubpc")
include(":free2air")
include(":share")
include(":tv")
include(":tdlib")
include(":telegram")
include(":previewimagcol")
