include(":gsmovies")
include(":eporner")
include(":2d")
include(":ets2mm")
include(":doujin")
include(":zcm")
include(":msys")
include(":msubpc")
include(":free2air")
include(":share")
include(":tv")
rootProject.name = "ATSY Cast"
