name: ATSY Cast Release Building

on:
  push:
    tags:
      - '*'

jobs:

  build_release:

    name: Build Release
    runs-on: ubuntu-18.04
    env:
      APP_CONFIG_FILE_BASE64: ${{ secrets.APP_CONFIG_FILE }}
      RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE }}
      RELEASE_PLAY_SERVICE_BASE64: ${{ secrets.RELEASE_PLAY_SERVICE }}
      FILE_UPLOAD_URL: ${{ secrets.FILE_UPLOAD_URL }}

    steps:

      - name: Check Out Branch
        uses: actions/checkout@v2.3.4

      - run: touch local.properties
      - run: echo $APP_CONFIG_FILE_BASE64 | base64 --decode > local.properties
      - run: touch release-keystore.jks
      - run: echo $RELEASE_KEYSTORE_BASE64 | base64 --decode > release-keystore.jks
      - run: touch tv/google-services.json
      - run: echo $RELEASE_PLAY_SERVICE_BASE64 | base64 --decode > tv/google-services.json

      - name: Tag Version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Release
        run: bash ./gradlew assembleprodRelease --stacktrace

      - name: Send Release APK to Tester
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ secrets.FIREBASE_RELEASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: release
          releaseNotesFile: RELEASE_NOTE.txt
          file: tv/build/outputs/apk/release/${{ env.RELEASE_VERSION }}/atsy-cast.apk

      - name: Upload Release APK to CDN
        uses: wei/curl@v1
        with:
          args: --location --request POST ${{ env.FILE_UPLOAD_URL }} -F 'file=@app/build/outputs/apk/release/${{ env.RELEASE_VERSION }}/atsy-cast.apk;type=application/vnd.android.package-archive' --form 'version=${{ env.RELEASE_VERSION }}' --form 'apk_name=ATSY Cast - New' --form 'file_name=atsy-cast' --form 'update_name=release'

      - name: Notift Release status
        if: always()
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.BOT_TOKEN }}
          chatId: ${{ secrets.KH_CHAT_ID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
